<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ExcelAccel.ExcelAddIn</AssemblyName>
    <RootNamespace>ExcelAccel.ExcelAddIn</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <ExcelDnaCreate32BitAddIn>false</ExcelDnaCreate32BitAddIn>
    <ExcelDnaCreate64BitAddIn>true</ExcelDnaCreate64BitAddIn>
    <ExcelDna64BitAddInSuffix>64</ExcelDna64BitAddInSuffix>
    <ExcelDnaPublishPath>publish</ExcelDnaPublishPath>
    <ExcelAddInInclude>ExcelAccel.Core.dll</ExcelAddInInclude>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExcelAccel.Core\ExcelAccel.Core.csproj" />
    <PackageReference Include="ExcelDna.AddIn" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
